services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: doday_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=OO__JOjo12germanic!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    image: doday_backend
    build:
      context: .
      dockerfile: DoDay/Dockerfile
    container_name: doday_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DoDayDBConnection=Server=db;Database=DoDayDB;User Id=sa;Password=OO__JOjo12germanic!;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    container_name: doday_front
    build:
      context: ../do_day(front-end)
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  seq:
    image: datalust/seq:latest
    container_name: doday-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=SEQpassword2333
    ports:
      - "5341:80"
      - "5342:5341"

volumes:
  sql_data:
